[package]
name = "hir_runnables"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
hir = { path = "../hir", version = "0.0.0" }
base_db = { path = "../base_db", version = "0.0.0" }